require("me.globals")
require("me.options")
require("me.remap")
require("me.lazy")
require("me.gruvbox")
require("me.lsp")

require("me.cmp")
require("me.comment")
require("me.none-ls")
--require("me.tmux")
require("me.autocommands")
require("me.autopairs")
require("me.fidget")
require("me.colorizer")
require("me.inlayhints")
require("me.todo")
