require("daslastic.globals")
require("daslastic.options")
require("daslastic.remap")
require("daslastic.lazy")
require("daslastic.gruvbox")
require("daslastic.lsp")

local function defer_init()
  require("daslastic.defer.comment")
  require("daslastic.defer.cmp")
  require("daslastic.defer.tmux")
  require("daslastic.defer.autocommands")
  require("daslastic.defer.gitsigns")
  require("daslastic.defer.illuminate")
  require("daslastic.defer.autopairs")
  require("daslastic.defer.fidget")
  require("daslastic.defer.null-ls")
  require("daslastic.defer.todo")
  require("daslastic.defer.zenmode")
  require("daslastic.defer.dap")
  require("daslastic.defer.colorizer")
  require("daslastic.defer.inlayhints")
  require("daslastic.defer.rt")
end

vim.defer_fn(defer_init, 30)
